require("nvim6.plugged")
require("nvim6.mappings")
require("nvim6.options")
require("nvim6.theme")

require("nvim6.plugins.autopairs")
require("nvim6.plugins.blankline")
require("nvim6.plugins.bufferline")
require("nvim6.plugins.colorizer")
require("nvim6.plugins.formatter")
require("nvim6.plugins.lspConfig")
require("nvim6.plugins.lspInstaller")
require("nvim6.plugins.lualine")
require("nvim6.plugins.nvimcmp")
require("nvim6.plugins.telescope")
require("nvim6.plugins.treesiter")
require("nvim6.plugins.trouble")
