require("nvim5.plugged")
require("nvim5.mappings")
require("nvim5.options")
require("nvim5.theme")

require("nvim5.plugins.blankline")
require("nvim5.plugins.bufferline")
require("nvim5.plugins.saga")
require("nvim5.plugins.lspInstaller")
require("nvim5.plugins.lspConfig")
require("nvim5.plugins.nvimcmp")
require("nvim5.plugins.treesiter")
require("nvim5.plugins.autopairs")
require("nvim5.plugins.telescope")
require("nvim5.plugins.colorizer")
require("nvim5.plugins.formatter")
