require("nvim5.plugged")
require("nvim5.mappings")
require("nvim5.options")
require("nvim5.theme")

require("nvim5.plugins.blankline")
require("nvim5.plugins.bufferline")
require("nvim5.plugins.saga")
require("nvim5.plugins.lspinstall")
require("nvim5.plugins.nvimcmp")
require("nvim5.plugins.treesiter")
require("nvim5.plugins.autopairs")
require("nvim5.plugins.telescope")
