require("nvim7.plugged")
require("nvim7.mappings")
require("nvim7.options")
require("nvim7.theme")

require("nvim7.plugins.autopairs")
require("nvim7.plugins.blankline")
require("nvim7.plugins.bufferline")
require("nvim7.plugins.colorizer")
require("nvim7.plugins.formatter")
require("nvim7.plugins.lspconfig")
require("nvim7.plugins.lspinstaller")
require("nvim7.plugins.statusline")
require("nvim7.plugins.completion")
require("nvim7.plugins.telescope")
require("nvim7.plugins.treesiter")
require("nvim7.plugins.trouble")
require("nvim7.plugins.gitsigns")
